### PR TITLE
feat(cloudformation): request and response models for custom resources

### PR DESCRIPTION
**Pull request by renatoaguimaraes**
Mapping `Request` and `Response` of [`CustomResource`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref.html) used by `Type: AWS::Lambda::Function`.

### Motivation:

Avoid to write repeated code for every Swift Lambda Function where is used a CustomResource to pass properties. Inspired on [event.go](https://github.com/aws/aws-lambda-go/blob/main/cfn/event.go) and [response.go](https://github.com/aws/aws-lambda-go/blob/main/cfn/response.go) from https://github.com/aws/aws-lambda-go.git.

### Modifications:

Added two new structs: [`Request`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requests.html) and [`Response`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html) for Lambda event triggered by CloudFormation.

### Result:

New models to be shared between Swift Lambda Functions that use [CustomResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref.html).

### CODE REVIEW

**Comment by tomerd** [comment]
thank you so much @renatoaguimaraes, would you mind adding a unit test following the examples of the other events

**Comment by renatoaguimaraes** [comment]
> thank you so much @renatoaguimaraes, would you mind adding a unit test following the examples of the other events

Sure, I will follow the existing examples. Thanks.

**Comment by renatoaguimaraes** [comment]
Hello @tomerd. Can you take a look?

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@renatoaguimaraes looks like the new tests are failing?

**Comment by renatoaguimaraes** [comment]
> @renatoaguimaraes looks like the new tests are failing?

Yes, there is one scenario failing. I'm running the new unit tests on Mac OS 12.3.1 + Swift 5.6.1 with success and the project pipeline is running the tests on swift:5.4-amazonlinux2. It seems to me an implementation detail that depends on the environment, where the order of attributes is changing for some reason. But that's ok, I'll think in another way to test this specific scenario.

Running on swift:5.4-amazonlinux2.

Expected:

`("Optional("{\"StackId\":\"arn:aws:cloudformation:us-east-1:123456789:stack\\/TestStack\",\"Reason\":\"See the details in CloudWatch Log Stream\",\"NoEcho\":false,\"Status\":\"SUCCESS\",\"LogicalResourceId\":\"TestLogicalResource\",\"RequestId\":\"cdc73f9d-aea9-11e3-9d5a-835b769c0d9c\",\"Data\":{\"property2\":\"\",\"property3\":[\"1\",\"2\",\"3\"],\"property1\":\"value1\"},\"PhysicalResourceId\":\"TestPhysicalResource\"}")") `

Result:

`("Optional("{\"NoEcho\":false,\"Data\":{\"property2\":\"\",\"property1\":\"value1\",\"property3\":[\"1\",\"2\",\"3\"]},\"StackId\":\"arn:aws:cloudformation:us-east-1:123456789:stack\\/TestStack\",\"LogicalResourceId\":\"TestLogicalResource\",\"Reason\":\"See the details in CloudWatch Log Stream\",\"Status\":\"SUCCESS\",\"RequestId\":\"cdc73f9d-aea9-11e3-9d5a-835b769c0d9c\",\"PhysicalResourceId\":\"TestPhysicalResource\"}")") `
 
Mac OS 12.3.1 + Swift 5.6.1

Expected 
`("Optional("{\"StackId\":\"arn:aws:cloudformation:us-east-1:123456789:stack\\/TestStack\",\"Reason\":\"See the details in CloudWatch Log Stream\",\"NoEcho\":false,\"Status\":\"SUCCESS\",\"LogicalResourceId\":\"TestLogicalResource\",\"RequestId\":\"cdc73f9d-aea9-11e3-9d5a-835b769c0d9c\",\"Data\":{\"property2\":\"\",\"property3\":[\"1\",\"2\",\"3\"],\"property1\":\"value1\"},\"PhysicalResourceId\":\"TestPhysicalResource\"}")") `

Result:

`{\"StackId\":\"arn:aws:cloudformation:us-east-1:123456789:stack\\/TestStack\",\"Reason\":\"See the details in CloudWatch Log Stream\",\"NoEcho\":false,\"Status\":\"SUCCESS\",\"LogicalResourceId\":\"TestLogicalResource\",\"RequestId\":\"cdc73f9d-aea9-11e3-9d5a-835b769c0d9c\",\"Data\":{\"property2\":\"\",\"property3\":[\"1\",\"2\",\"3\"],\"property1\":\"value1\"},\"PhysicalResourceId\":\"TestPhysicalResource\"}")`

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
@renatoaguimaraes looks like some formatting issues left - you can fix that locally by running the formatting task in docker

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thank you @renatoaguimaraes

**Comment by renatoaguimaraes** [comment]
> thank you @renatoaguimaraes

Thank you. It is my pleasure to contribute to the project.

**Pull request merged**
