### PR TITLE
remove support for versions of Swift <= 5.6

### PR DESCRIPTION
**Pull request by sebsto**
fix https://github.com/swift-server/swift-aws-lambda-events/issues/31

### CODE REVIEW

**Comment by sebsto** [comment]
@adam-fowler can you review ?

**Comment by sebsto** [comment]
@adam-fowler It's just the first line that sets the minimum required version of the toolchain.

Aren't these necessary if someone tries to compile with a specific toolchain ?

What would be the alternative ?
Have only one `Package.swift` with the minimum version we support, like 

```
// swift-tools-version:5.7
```

What is the best practice to follow ?

**Comment by adam-fowler** [comment]
If there are no other differences a single Package.swift with `// swift-tools-version:5.7` would be fine. It basically implies the minimum swift version we accept. 

But as I said it may be worthwhile setting the minimum to 5.8. This would allows us to setting strict concurrency flags as well.

**Comment by sebsto** [comment]
@adam-fowler what about now ?

I'll create another PR to add 
```
swiftSettings: [.enableExperimentalFeature("StrictConcurrency")]
```

Because it requires additional changes in the code

**Comment by adam-fowler** [comment]
We'll need to remove the 5.7 CI. @yim-lee  can you help here please

**Comment by sebsto** [comment]
@adam-fowler should I wait for the CI to be updated to merge ?

**Comment by adam-fowler** [comment]
> @adam-fowler should I wait for the CI to be updated to merge ?

Any idea what is happening with the examples CI?

**Comment by sebsto** [comment]
What are the examples CI ?

**Comment by adam-fowler** [comment]
> What are the examples CI ?

I don't know but at the moment it is failing. It's called `pull request validation (examples)`. It looks like it is dependent on 5.7 docker image. Should probably be 5.10. I cannot find where this is setup though

**Comment by sebsto** [comment]
@swift-server-bot test this please

**Comment by sebsto** [comment]
@yim-lee Can you also update the `pull request validation (examples)` CI to use Swift 5.10 docker files ?
Right now, it seems to use 5.7 

```
17:41:15 + docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.al2.57.yaml -p swift-aws-lambda-events-samples-prb build --pull
17:41:16 .FileNotFoundError: [Errno 2] No such file or directory: './docker/docker-compose.al2.57.yaml'
```

Thank you

**Comment by yim-lee** [comment]
Deleted CI for Swift 5.7. Updated examples CI to use Swift 5.10.

@swift-server-bot test this please

**Comment by sebsto** [comment]
@yim-lee Thank you for the update.
Any idea why 5.7 is failing ? We can't access the server logs :-( 
image

**Comment by yim-lee** [comment]
@sebsto The 5.7 pipeline has been deleted, so it doesn't get run anymore. The failure you see on this page is previous result, but because we don't run that pipeline anymore the status won't get updated.

Someone with admin permissions will need to update branch rules in this repo's settings to remove old Swift versions and make new ones required.

**Comment by sebsto** [comment]
Looks like I have permissions to do that.
I removed 5.7 and added 5.8 as required check

@swift-server-bot test this please

**Comment by sebsto** [comment]
@adam-fowler a last check before merging ? Thank you

**Review by adam-fowler — APPROVED** [review]
LGTM
StructConcurrency setting should really be `.enableExperimentalFeature("StrictConcurrency=complete")` though.

**Pull request merged**
