### PR TITLE
Add Authorizer struct to APIGateway Event

### PR DESCRIPTION
**Pull request by richwolf**
Add an `Authorizer` struct to the `APIGateway` (v1) event

### Motivation:

When setting up an API Gateway REST API (as opposed to the v2 HTTP API) with Lambda integration, a resource endpoint can be configured to use "Lambda Proxy Integration"…which results in the v1-style `APIGatewayRequest` event object being sent to a Swift Lambda handler (as opposed to the `APIGatewayV2Request` object, which gets sent whenever API Gateway is configured as an "HTTP" API). The `APIGatewayRequest` event struct does not decode an `authorizer`…which is included within Lambda Proxy Integration JSON whenever Cognito is attached to REST endpoints. The `authorizer` contains a `claims` dictionary (very much like the one found in the `APIGatewayV2Request` object):

```
  claims: {
    sub: '2592124a-27bf-4e30-b95f-2f21c862fc82',
    event_id: 'fbf7193a-e3b4-462b-95b4-4df60a9fe410',
    token_use: 'access',
    scope: 'aws.cognito.signin.user.admin phone openid profile email',
    auth_time: '1683085806',
    iss: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pxAHZcSSX',
    exp: 'Thu May 04 03:50:06 UTC 2023',
    version: '2',
    iat: 'Wed May 03 03:50:06 UTC 2023',
    client_id: '6rupb256qn12tju82occ9eppqr',
    jti: '5d92ca29-677e-40d9-a074-2d86fbcb4023',
    username: 'richwolf'
  }
```

Just as with the `APIGatewayV2` event, the claims dictionary would be useful to Swift Lambda event handlers (particularly because it contains the Cognito username authorized to invoke an API endpoint).

### Modifications:

I added an (optional) `Authorizer` struct to the `APIGatewayRequest` object. The struct contains a single public property…an optional `claims` object (dictionary of type `[String: String]` in a way that mirrors the authorizer implementation in the `APIGatewayV2Request` object. 

### Result:

The `APIGatewayRequest` object now successfully decodes the `authorizer` sent by the Lambda Proxy Integration JSON and can be used within a Swift Lambda event handler.

### CODE REVIEW

**Comment by tomerd** [comment]
looks good. can we update / add a test?

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thanks for this @richwolf looks like the soundness job is failing due to formatting issue. you can run it locally to get this all lined up:

`docker-compose -f docker/docker-compose.yaml run --rm soundness`

**Comment by richwolf** [comment]
Yeah, it doesn't surprise me that there could be a formatting issue. I have my Xcode set to 2 space tabs, but notice that the project is 2 space ... uh ... spaces. I thought I caught all the tabs, but maybe not? Running the soundness thingy now. Very cool tool. :)

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
thanks @richwolf

**Pull request merged**
