### PR TITLE
Add EventBridge S3Events notifications

### PR DESCRIPTION
**Pull request by ugocottin**
Add EventBridge S3Events notifications

### Motivation:

I want to handle S3 event notifications sent via EventBridge with a Lambda. These events are not defined.

### Modifications:

Based on [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventBridge.html), I've added the following events:
- Object Created
- Object Deleted
- Object Restore Initiated
- Object Restore Completed
- Object Restore Expired
- Object Storage Class Changed
- Object Access Tier Changed
- Object ACL Updated
- Object Tags Added
- Object Tags Deleted

I've also added tests for S3 events with examples on S3 [EventBridge event message structure](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ev-events.html).

### Result:

You can now handle S3 events notifications from EventBridge!

### CODE REVIEW

**Comment by ugocottin** [comment]
Hi @MahdiBM,

Thanks for the tip, but the goal here is to trigger a Lambda **through** EventBridge, I'm not making any call **to** EventBridge API. Perhaps for calling S3 API, yes, but now that [AWS SDK of Swift](https://github.com/awslabs/aws-sdk-swift) is GA, I prefer to use AWS SDK rather than Soto.

**Comment by MahdiBM** [comment]
@ugocottin ah I see.

FWIW Soto has been working great for us, and it's still likely a better choice for Swift on Server considering it properly integrates with all the Server Side Swift stuff.
Like using packages that are based on SwiftNIO, which are a better fit for Server Side. Things like using AsyncHTTPClient and not relying on URLSession.

**Comment by sebsto** [comment]
@swift-server-bot test this please

**Review by sebsto — APPROVED** [review]
LGTM

**Comment by sebsto** [comment]
Thank you @ugocottin for this change.  Now merged

**Pull request merged**
